{{- if .Values.deviceClass.create }}
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: {{ .Values.deviceClass.name }}
  labels:
    {{- include "linux-net-dra.labels" . | nindent 4 }}
spec:
  selectors:
    - cel:
        expression: >-
          device.driver == {{ .Values.driverName | squote }} &&
          device.attributes[{{ printf "%s/interface" .Values.driverName | squote }}].string == {{ .Values.deviceClass.interfaceName | squote }} &&
          {{ .Values.deviceClass.type | squote }} in device.attributes[{{ printf "%s/types" .Values.driverName | squote }}].string.split(',')
{{- end }}
