apiVersion: v2
name: linux-net-dra
description: Kubernetes DRA driver for Linux netdevices and userspace DPDK devices without Multus or CNI attachments
type: application
version: 0.3.2
appVersion: "0.3.2"
