apiVersion: v2
name: linux-net-dra
description: Kubernetes DRA driver for Linux macvlan and ipvlan pod interfaces without Multus or CNI attachments
type: application
version: 0.1.5
appVersion: "0.1.5"
